### ISSUE TITLE
Feature Request: Aqara Door Window Sensor Temperature

### ISSUE THREAD

**Issue by mercenaryballs** [Kane610/deconz#10]
Thanks for your work with adding deconz support to HA!

I noticed that deconz now reports temperature from the xiaomi aqara door/window sensors. Would it be possible to bring this data into home assistant?

Phoscon:
![image](https://user-images.githubusercontent.com/34362886/38640835-64fda8d4-3da3-11e8-9d18-8309a4e980da.png)

json from the deconz
https://pastebin.com/Ac7vkp1j

**Comment by Kane610** [comment]
Thanks for that kind feedback!

First! I'd recommend you open an issue with the deconz rest api GitHub. I'd prefer if deconz handle this in the same way as with hue motion sensors and other devices with multiple sensors; they create one device per sensor. If they don't want that, I'd be happy to look in to handle it in this library

/R

**Comment by Kane610** [comment]
I am improving pydeconz to map all attributes of devices (including this temperature value) so it will be added to hass in release 88 or 89.
