### ISSUE TITLE
[FR] Add support for Lidl Smart Wireless Door Bell 

### ISSUE THREAD

**Issue by T0mWz** [Kane610/deconz#124]
Should be nice if the Lidl Smart Wireless Door Bell supported with triggers within Home Assistent.
See also my issue at deconz-rest-plugin git repo; https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4450

The Lidl Smart Wireless Door Bell  only contains one button. 

Device registry; 
```
2021-06-16 11:07:50 DEBUG (MainThread) [pydeconz.websocket] {"attr":{"id":"14","lastannounced":"2021-05-18T10:56:46Z","lastseen":"2021-06-16T09:07Z","manufacturername":"EcoDim BV","modelid":"Dimmer-Switch-ZB3.0","name":"Slaapkamer T&I spotjes","swversion":"3.09","type":"Dimmable light","uniqueid":"08:6b:d7:ff:fe:5d:75:98-01"},"e":"changed","id":"14","r":"lights","t":"event","uniqueid":"08:6b:d7:ff:fe:5d:75:98-01"}

2021-06-16 11:07:52 DEBUG (MainThread) [pydeconz.websocket] {"e":"added","id":"53","r":"sensors","sensor":{"config":
{"battery":null,"enrolled":0,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"c0d25a498684b0634797d3d79aa45ef1","id":"53","lastseen":"2021-06-16T09:07Z","manufacturername":"LIDL Silvercrest","mode":1,"modelid":"HG06668","name":"Switch 53","state":

{"buttonevent":null,"lastupdated":"none","lowbattery":false,"tampered":false},"type":"ZHASwitch","uniqueid":"84:2e:14:ff:fe:f9:4a:ca-01-0500"},"t":"event","uniqueid":"84:2e:14:ff:fe:f9:4a:ca-01-0500"}
2021-06-16 11:07:52 DEBUG (MainThread) [pydeconz.deconzdevice] Switch 53 created as
{'config': {'battery': None,
            'enrolled': 0,
            'on': True,
            'pending': [],
            'reachable': True},
 'ep': 1,
 'etag': 'c0d25a498684b0634797d3d79aa45ef1',
 'id': '53',
 'lastseen': '2021-06-16T09:07Z',
 'manufacturername': 'LIDL Silvercrest',
 'mode': 1,
 'modelid': 'HG06668',
 'name': 'Switch 53',
 'state': {'buttonevent': None,
           'lastupdated': 'none',
           'lowbattery': False,
           'tampered': False},
 'type': 'ZHASwitch',
 'uniqueid': '84:2e:14:ff:fe:f9:4a:ca-01-0500'}
```

On button press
```
2021-06-16 11:08:01 DEBUG (MainThread) [pydeconz.websocket] {"e":"changed","id":"53","r":"sensors","state":
{"buttonevent":1002,"lastupdated":"2021-06-16T09:08:01.838","lowbattery":false,"tampered":false},"t":"event","uniqueid":"84:2e:14:ff:fe:f9:4a:ca-01-0500"}

```

**Comment by T0mWz** [comment]
Don't want to get in your way of development.  Not entirely clear to me where I can easily create the merge for this. Directly in the Home Assistant git project?

But here is the code;

```
LIDL_SILVERCREST_DOORBELL_MODEL = "HG06668"
LIDL_SILVERCREST_DOORBELL = {
    (CONF_SHORT_PRESS, ""): {CONF_EVENT: 1002},
}

..
..
REMOTES = {
..
LIDL_SILVERCREST_DOORBELL_MODEL: LIDL_SILVERCREST_DOORBELL,
...

}

```

Have already tested it;
![Doorbell](https://user-images.githubusercontent.com/2477797/122200952-cf69c400-ce9b-11eb-8947-b83ffc271805.png)

**Comment by Kane610** [comment]
Congratulations!

**Comment by boehser-enkel** [comment]
There is still no button available. Just a tampered sensor which does not respond to button press. Is that intended?

**Comment by Kane610** [comment]
> There is still no button available. Just a tampered sensor which does not respond to button press. Is that intended?

The button is only an event just like all other remotes. The above mentioned PR adds device triggers to automations, you will get it listed in automations but there won't be an entity for the button itself

**Comment by boehser-enkel** [comment]
> > There is still no button available. Just a tampered sensor which does not respond to button press. Is that intended?
> 
> The button is only an event just like all other remotes. The above mentioned PR adds device triggers to automations, you will get it listed in automations but there won't be an entity for the button itself


thanks for the fast answer. Yes but I have no button trigger to select for automations and I get the same event (0) on press as mentioned above

**Comment by T0mWz** [comment]
@boehser-enkel What automation tool are you using? Or only Deconz?

**Comment by T0mWz** [comment]
Ow wait, home assistent ofcourse. Then you should be able to create an trigger like this;
![LidlWirelessDoorbell](https://user-images.githubusercontent.com/2477797/157237913-012c8b65-0764-46fd-8fd4-2ef5fb6d5bdf.png)

**Comment by boehser-enkel** [comment]
> @boehser-enkel What automation tool are you using? Or only Deconz?

Home Assistant. But also in Phoscon I am not able to choose it as a button

**Comment by boehser-enkel** [comment]
there is only tampered and battery

![E29E7829-3974-4F72-A711-3BE07DA703DB](https://user-images.githubusercontent.com/59539881/157238257-344053f0-32d2-4113-ba12-d0c7659426fa.jpeg)

**Comment by T0mWz** [comment]
Hm. Which version of HA & Deconz are you using?

**Comment by boehser-enkel** [comment]
> Hm. Which version of HA & Deconz are you using?

2022.3.2 & 2.14.01

**Comment by T0mWz** [comment]
Strange, it's still in the code. Do you see the events in the logs of deconz and home assistent?

**Comment by boehser-enkel** [comment]
> Strange, it's still in the code. Do you see the events in the logs of deconz and home assistent?

I see the events in HA. Don’t know where to look in Phoscon to be honest

**Comment by Kane610** [comment]
Has the model id changed? Right now it's expected to be "HG06668"

**Comment by boehser-enkel** [comment]
> Has the model id changed? Right now it's expected to be "HG06668"

It’s the same

**Comment by Kane610** [comment]
> > Has the model id changed? Right now it's expected to be "HG06668"
> 
> It’s the same

Can you share a diagnostics file from the integration?

**Comment by boehser-enkel** [comment]
> > > Has the model id changed? Right now it's expected to be "HG06668"
> > 
> > 
> > It’s the same
> 
> Can you share a diagnostics file from the integration?

U mean the Home Assistant Deconz Integration diagnostic file?

**Comment by Kane610** [comment]
Exactly

**Comment by boehser-enkel** [comment]
[config_entry-deconz-26968d9235b79c6841870ed86d4a94fe.json.txt](https://github.com/Kane610/deconz/files/8602415/config_entry-deconz-26968d9235b79c6841870ed86d4a94fe.json.txt)
Here you go

**Comment by T0mWz** [comment]
Strange, in your diagnostics the device is recognized as TS0211, instead of HG06668
For example my output;
```
      "54": {
        "config": {
          "battery": null,
          "enrolled": 1,
          "on": true,
          "pending": [],
          "reachable": true
        },
        "ep": 1,
        "etag": "80c742102fab2bb3da6a6b08cf363e32",
        "lastannounced": "2022-03-24T12:44:47Z",
        "lastseen": "2022-04-04T13:21Z",
        "manufacturername": "LIDL Silvercrest",
        "mode": 1,
        "modelid": "HG06668",
        "name": "Switch 54",
        "state": {
          "buttonevent": 1002,
          "lastupdated": "2022-04-28T13:10:13.704",
          "lowbattery": false,
          "tampered": false
        },
        "type": "ZHASwitch",
        "uniqueid": "84:2e:14:ff:fe:f6:d5:ea-01-0500",
        "attr": {
          "id": "54",
          "lastannounced": "2022-03-24T12:44:47Z",
          "lastseen": "2022-05-02T10:50Z",
          "manufacturername": "LIDL Silvercrest",
          "modelid": "HG06668",
          "name": "Switch 54",
          "swversion": null,
          "type": "ZHASwitch",
          "uniqueid": "84:2e:14:ff:fe:f6:d5:ea-01-0500"
        },
        "e": "changed",
        "id": "54",
        "r": "sensors",
        "t": "event"
      },
```

**Comment by boehser-enkel** [comment]
This is strange. Even on the device itself its printed HG06668.
Any way to work around this?

**Comment by T0mWz** [comment]
Can you try to add here https://github.com/home-assistant/core/blob/dev/homeassistant/components/deconz/device_trigger.py#L480
```
LIDL_SILVERCREST_DOORBELL_MODEL2 = "TS0211"
```

And then here; https://github.com/home-assistant/core/blob/dev/homeassistant/components/deconz/device_trigger.py#L609
```
    LIDL_SILVERCREST_DOORBELL_MODEL2: LIDL_SILVERCREST_DOORBELL,
```


or just change HG06668 for TS0211.

**Comment by boehser-enkel** [comment]
I can't find these files in my (supervised container) installation. 
Won't they be overwritten on the next update anyways?

**Comment by T0mWz** [comment]
I haven't experience with the supervisor setup, but can you access the Home Assistent container?
`docker exec -it $(docker ps -f name=homeassistant -q) bash`

Then I guess Home Assistent is in `/usr/src/homeassistant/homeassistant` or `/usr/share/hassio/homeassistant`.
But try otherwise a find; `find / -name deconz`

**Comment by boehser-enkel** [comment]
okay it's in /usr/src/homeassistant/homeassistant. But i dont even have a text editor inside the container. Also after a reboot changes would be gone

**Comment by boehser-enkel** [comment]
Changed it and did a restart of HA. Now i can select  "button pressed" but it won't get recognized when i press the doorbell

**Comment by T0mWz** [comment]
But do you see this event on Deconz self? Wondering of there is not more different then only the device identifier.
```
docker logs -f --tail 100  $(docker ps -f name=deconz -q)
```

**Comment by boehser-enkel** [comment]
I run Phoscon on a seperate device directly installed (no docker)

**Comment by boehser-enkel** [comment]
What do i have to look for?
I found this: 
`15:16:11:297 DEV no DDF for 0x842E14FFFEF6E87B, modelId: TS0211
15:16:11:297 DEV create on-the-fly DDF for 0x842E14FFFEF6E87B`

**Comment by T0mWz** [comment]
Hmm; `No button map for: TS0211`.  So I guess you don't see a log message in deconz when you pushed the button, right?

**Comment by Kane610** [comment]
> No button map for: TS0211

That would mean you can either create a DDF for the file or request device support on the forums

**Comment by T0mWz** [comment]
Updated my deconz container, where after button mapping was broken. Here is the request in deconz;
```
12:09:21:872 [INFO] - No button handler for: HG06668, unicast to: 0x0000, endpoint: 0x01, cluster: IAS_ZONE (0x0500), command: STATUS_CHANGE (0x00), payload: 0D0000640000, zclSeq: 74
12:09:21:873 Websocket 172.21.0.5:47964 send message: {"e":"changed","id":"54","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2022-12-14T11:09:21.871"},"t":"event","uniqueid":"84:2e:14:ff:fe:f6:d5:ea-01-0500"} (ret = 165)
12:09:21:874 Websocket 172.21.0.5:44130 send message: {"e":"changed","id":"54","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2022-12-14T11:09:21.871"},"t":"event","uniqueid":"84:2e:14:ff:fe:f6:d5:ea-01-0500"} (ret = 165)
12:09:21:875 Websocket 172.23.0.18:58272 send message: {"e":"changed","id":"54","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2022-12-14T11:09:21.871"},"t":"event","uniqueid":"84:2e:14:ff:fe:f6:d5:ea-01-0500"} (ret = 165)
12:09:21:877 Websocket 172.23.0.18:58282 send message: {"e":"changed","id":"54","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2022-12-14T11:09:21.871"},"t":"event","uniqueid":"84:2e:14:ff:fe:f6:d5:ea-01-0500"} (ret = 165)
12:09:21:878 Websocket 172.21.0.5:52864 send message: {"e":"changed","id":"54","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2022-12-14T11:09:21.871"},"t":"event","uniqueid":"84:2e:14:ff:fe:f6:d5:ea-01-0500"} (ret = 165)
12:09:21:879 APS-DATA.request id: 161, addrmode: 0x02, addr: 0xa888, profile: 0x0104, cluster: 0x0500, ep: 0x01 -> 0x01 queue: 2 len: 5 tx.options 0x04
```

Device visible within HA;
![Screenshot 2022-12-14 at 12 14 57](https://user-images.githubusercontent.com/2477797/207581104-2b12f322-dc0b-4a60-9c1e-766bc206f2dc.png)

Previous trigger setup;
![Screenshot 2022-12-14 at 12 14 37](https://user-images.githubusercontent.com/2477797/207581175-d63c2698-0b5f-4e6c-9097-57b083ea2501.png)

New trigger;
![Screenshot 2022-12-14 at 12 16 51](https://user-images.githubusercontent.com/2477797/207581442-92fbea47-1c24-48f0-8f80-02a1d75f461c.png)


Can you check of this works too for you, @boehser-enkel  ?

**Comment by funker** [comment]
Sorry for posting in this old old thread, but have you been able to get it working? 

Back in the days I was able to trigger Alexa with this, but the automation is gone and I don't know how to get it fixed.

I get this in the logs

```
"71": {
        "config": {
          "battery": 0,
          "on": true,
          "pending": [],
          "reachable": true
        },
        "ep": 1,
        "etag": "374b0fc960eef220d96229f3f9611008",
        "lastannounced": null,
        "lastseen": "2024-01-07T10:48Z",
        "manufacturername": "LIDL Silvercrest",
        "mode": 1,
        "modelid": "TS0211",
        "name": "Button A01",
        "state": {
          "buttonevent": 1002,
          "lastupdated": "2024-01-09T13:01:10.136"
        },
        "type": "ZHASwitch",
        "uniqueid": "84:2e:14:ff:fe:f9:46:f2-01-0500"
      },
```

And I also get events being fired, but still, I can neither select something relevant in automations nor do I see the battery state (which I replaced an hour ago).

![image](https://github.com/Kane610/deconz/assets/3451013/17665265-9497-4a47-9305-dd6905530d73)

I'm using HA 2024.1.2 and deconz 2.24.2.

Would appreciate any feedback as these device lay around for almost two years now and I want to start using them ;-)

**Comment by Kane610** [comment]
It looks like the TS0211 model id has been added to deconz so we should be able to support this now that it has button mappings

**Comment by Kane610** [comment]
PR is up, should be supported with next major HA release.
