### ISSUE TITLE
Sensor precision, number of decimals

### ISSUE THREAD

**Issue by ACrazyConcept** [Kane610/deconz#127]
Hi

I just made a post on the HA forum about the sensor values of deCONZ being rounded to 1 decimal even though the deCONZ REST API contains 2 decimals: https://community.home-assistant.io/t/deconz-sensors-precision-rounded-to-1-decimal/318506
But now I found this repo and I assume this is where the rounding is taking place?

Would it be an option to include the two available decimals for temperature and humidity?

![image](https://user-images.githubusercontent.com/36438756/123554854-6418cf80-d782-11eb-9473-d2206449c1ff.png)
![image](https://user-images.githubusercontent.com/36438756/123554856-6713c000-d782-11eb-84d4-a0fca4ea7cfe.png)

**Comment by Kane610** [comment]
Why would you need two decimals of precision? The sensors aren't calibrated anyway so even one decimal is generous here :)

**Comment by ACrazyConcept** [comment]
Mainly because it is there. It was made available in the device firmware and in the deCONZ REST API. Of course I acknowledge that precision<>accuracy and that this might be nitpicking and I am totally fine either way :)
It just seems more correct to provide the values that are actually there and let people round them in HA if they want to.

I am doing some testing atm and I can see that I get slightly more readings and by that a smoother graph for some sensors.

I have tried to "calibrate" by setting the offset value via the REST API.
![image](https://user-images.githubusercontent.com/36438756/123623864-38432b80-d80e-11eb-9e27-57690493d9ab.png)

**Comment by Kane610** [comment]
Interesting. I could Probably change it in the lib but since it's been like this for a long time I should still limit the resolution on hass side as not to break possible automations.

The more I think about it trying to respond here I'm not certain changing it would affect anyone negatively. Could possibly be used together with significant change logic in hass to not trigger too many updates to the state machine.

This requires more thought

**Comment by ACrazyConcept** [comment]
Sure thing. No rush about it. Let me know if I can assist with some testing if it gets to that.

**Comment by ACrazyConcept** [comment]
Hi @Kane610 
Have you given this any further thoughts?

**Comment by Kane610** [comment]
Not yet, but I'm doing nearly a full rewrite of the library and those changes might affect this as well

**Comment by Kane610** [comment]
This has been solved 🎉
