### ISSUE TITLE
Support for HA Long Term Statistics

### ISSUE THREAD

**Issue by eggman0131** [Kane610/deconz#140]
Please could you find time to add support for Home Assistant Long Term Statistics, for Deconz Sensors?

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by Kane610** [comment]
I'll have a look

**Comment by eggman0131** [comment]
Feeling stupid, it looks like they work already.  I was expecting to see something different.

**Comment by Kane610** [comment]
Best kind of request 😂
