### ISSUE TITLE
How do I read the any_on and all_on states?

### ISSUE THREAD

**Issue by FezVrasta** [Kane610/deconz#19]
I know this library exposes them to Hass, but how do I get them in Hass? My DeCONZ exposed light groups don't have such attributes, and neither the Hass light groups.

**Comment by Kane610** [comment]
It will be part of the release this weekend. The main state is any_on. Then there is a property for all_on.

**Comment by FezVrasta** [comment]
Oh I see thank you so much, I thought it was already in. Great.
