### ISSUE TITLE
Expose switches as switches rather than bulbs?

### ISSUE THREAD

**Issue by FezVrasta** [Kane610/deconz#20]
Right now the switches (like the Osram Smart Plug) are exposed to Hass as bulbs, is this something that can be changed?

I understand they are listed under lights in DeCONZ, but they have a different icon (so DeCONZ knows they are not lights) and it's particularly annoying to have them together with the lights in Hass.

**Comment by Kane610** [comment]
Upgrade to the new hass version ;)

**Comment by FezVrasta** [comment]
This world is too fast for me 😣

Thanks! :-)
