### ISSUE TITLE
Entity registrations are not reflected in home assistant

### ISSUE THREAD

**Issue by winemug** [Kane610/deconz#21]
If a light/switch/sensor is added to the deconz network while home assistant is already running; it doesn't get reported. Home-assistant needs to be restarted for it to recognize the newly added component.

This is particularly painful, if deconz and home-assistant are started one after the other. Because the deconz rest plugin does not report any lights unless it has been discovered first. (even if they are already registered in the db to belong to the network) As a result, any component that was not discovered yet during startup, will never show on home-assistant.

**Comment by Kane610** [comment]
I've been thinking about a service in hass to load new entities, I have it started for sensors which is added automatically when registered to deconz.

I have some other things I've got going on, but will look into this in a reasonable time.

**Comment by Kane610** [comment]
PR is up to solve this, closing issue.
