### ISSUE TITLE
Expose CLIPGenericFlag sensors from deCONZ as switches to Home Assistant

### ISSUE THREAD

**Issue by Krocko** [Kane610/deconz#219]
Would it be possible to expose the CLIPGenericFlag sensors from deCONZ as switches to Home Assistant? So we can toggle it from Home Assistant. 
This can be useful to activate/deactivate rules or device in deCONZ. Or you can use it to toggle home/away in deCONZ.

**Comment by Kane610** [comment]
Sorry I wasn't clear, what I need are the raw data on how this would work so I can implement it properly. Closing this in favour of keeping https://github.com/Kane610/deconz/issues/14 open
