### ISSUE TITLE
Add support for "Range extender" light type

### ISSUE THREAD

**Issue by Kane610** [Kane610/deconz#230]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4175
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1095

https://github.com/dresden-elektronik/deconz-rest-plugin/commit/627a742de94ad2021133d946c79a013f2b885b08

Add new light handler similar to configuration tool
The Ikea extender seems to have support for "alert"

Could be exposed in Home Assistant as a binary sensor with device class "connectivity" or as a device tracker entity

**Comment by Kane610** [comment]
Basic support has been added, seems that alert can be used with certain range extenders so there is room for extending the support in the future.

**Comment by TheAlphaLaw** [comment]
> Basic support has been added, seems that alert can be used with certain range extenders so there is room for extending the support in the future.

Great, thank you!!!
