### ISSUE TITLE
Forward reachable events to HomeAssistant

### ISSUE THREAD

**Issue by mwhrtin** [Kane610/deconz#24]
Is it possible to somehow forward received reachable events to HomeAssistant? 

Whenever a light is powered on I see these prints in the HomeAssistant logs:

    [pydeconz.deconzdevice] my_deconz_light: update reachable with True
    [pydeconz.websocket] Websocket data: {"e":"changed","id":"1","r":"lights","state":{"reachable":true},"t":"event","uniqueid":":aa:bb:cc:dd:ee:ff-01"}

From the looks of it deCONZ is always sending an updated `reachable: true` when the light is powered on, even if the light's previous reachable state was `true` in the Rest API. But it appears as if HomeAssistant is unaware of this reachable update.

I would like to be able to trigger an automation in HomeAssistant when a reachable change message is received. Is it possible to forward this to HomeAssistant somehow, trigger a state update or something?

**Comment by Kane610** [comment]
They are. So hass can tell user if they're available or unavailable

**Comment by bedaes** [comment]
Is there a solution to this? I'm facing the exact same issue. I already asked at [Home Assistant Community](https://community.home-assistant.io/t/how-to-react-to-pydeconz-reachable-true-event/118748), but no reponse.

**Comment by Kane610** [comment]
Well. All I know is written above. I'd say you should create an issue on deconz github since the behavior as far as I know is correct with the hass implementation. 

If you could share logs that explicitly point to this issue can be improved with the component I will of course help you
