### ISSUE TITLE
Feature Request: Sensor type ZHACarbonMonoxide support

### ISSUE THREAD

**Issue by obousque** [Kane610/deconz#30]
The [Heiman HS1CA Smart Carbon Monoxide](http://www.heimantech.com/product/81.html) is supported by deconz but isn't by the home assistant deconz wrapping library.

`2019-04-22 19:40:46 INFO (MainThread) [pydeconz.sensor] Unsupported sensor type ZHACarbonMonoxide`

Here is the json/rest call result
``` 
 {
    'config': {
        'battery': 100,
        'on': True,
        'pending': [],
        'reachable': True
    },
    'ep': 1,
    'etag': 'XXX',
    'manufacturername': 'Heiman',
    'modelid': 'CO_V16',
    'name': 'Cave, CO',
    'state': {
         'carbonmonoxide': False,
         'lastupdated': 'none',
         'lowbattery': False,
         'tampered': False
    },
    'swversion': '20150330',
    'type': 'ZHACarbonMonoxide',
    'uniqueid': 'XXX'
}
```

**Comment by Kane610** [comment]
Awesome! I will have a look at this within a couple of days

**Comment by Kane610** [comment]
Im guessing it is a binary sensor since carbonmonoxide: False?

**Comment by Kane610** [comment]
Completed
