### ISSUE TITLE
Feature request: expose more Aqara FP1 functions to Home Assistant

### ISSUE THREAD

**Issue by freddieleeman** [Kane610/deconz#364]
The Aqara FP1, when paired through deCONZ with the deCONZ Home Assistant integration, exposes a single binary presence sensor. Device settings and other sensors are not exposed. When the presence sensor is connected through ZHA, the integration in HA looks like this:

![image](https://user-images.githubusercontent.com/6225998/186261187-1549b0e5-4d6c-47a0-a558-7c35be17fc15.png)

I've also found this zigbee2mqtt integration (though not working correctly):

![image](https://user-images.githubusercontent.com/6225998/186261599-9d816031-ed1f-4ead-ac73-24fe4bd81dcf.png)

Device details:
![image](https://user-images.githubusercontent.com/6225998/186262993-ea83a883-0af2-4052-94c4-e616079fa880.png)

The FP1 is capable of exciting things that I haven't been (easily) able to play with due to the absence of these settings and sensors. Thank you for your contributions to the smart-home community.

**Comment by Yuke-hd** [comment]
Hi @freddieleeman 
I have the same sensor and have been trying to figure out how the code works.
So far I've managed to add a new entity that shows the detection sensitivity (not configurable atm)
<img width="780" alt="image" src="https://user-images.githubusercontent.com/38873367/186553255-a126be77-e7ea-43bc-a82b-d44b7cbcdf06.png">

I'm actively trying to implement all to available feature. ETA is 2-3 weeks depending on how busy my day job is.

**Comment by Kane610** [comment]
Aqara FP1 support merged and will be part of 2022.9 beta coming today. Try it out please

**Comment by Kane610** [comment]
Closing this as I assume its good enough for now.

**Comment by freddieleeman** [comment]
Sorry, I meant to test it thoroughly, but life got in the way. It looks and works great! However, I wonder what the "Device Mode" does and why someone would use the "Reset Presence" feature.

**Comment by Kane610** [comment]
> Sorry, I meant to test it thoroughly, but life got in the way. It looks and works great! However, I wonder what the "Device Mode" does and why someone would use the "Reset Presence" feature.

My guess is that device mode will decide if it will react on all directions or just left<->right direction

Reset presence, I don't know. I just did the same as ZHA implementation :)
