### ISSUE TITLE
Sensors are added to deConz but are not appearing in HA

### ISSUE THREAD

**Issue by RZANDBER2006** [Kane610/deconz#384]
When i add a temp / hygro sensor via phoscon, the sensor is displayed you can see the values changing, i can see it in deconz. But when i reload the integration to get the sensors in home assistant i cant see the entity's in HA.

![tempsensor](https://user-images.githubusercontent.com/117517737/204515287-0edfac9f-f9c8-48b3-83e7-b11540a6f898.png)

**Comment by RZANDBER2006** [comment]
![image](https://user-images.githubusercontent.com/117517737/204515440-702f755b-b77e-4848-ae31-f28b78f00c39.png)

**Comment by Kane610** [comment]
Can you enable debug logging for the deconz integration and share the log output, instructions are on the deconz integration documentation page

**Comment by RZANDBER2006** [comment]
I'm not sure where to put the yaml code for the debugging? I pasted it in the configuration yaml? now restarted.  The next step is to share my logbook? where can i get this? in visual studio? I'm a complete NOOB at this.

**Comment by RZANDBER2006** [comment]
I also have found a debug view in deconz, is that the log you mean?

![image](https://user-images.githubusercontent.com/117517737/204768503-3156bb51-1ab5-4995-864e-80a65838375d.png)

**Comment by KennethLavrsen** [comment]
@RZANDBER2006 this is the debug info you are asked for

https://www.home-assistant.io/integrations/deconz/

and yes it goes in configuration.yaml

The HA integration developer needs to see what he receives from Deconz through the connection from HA to deconz. He obviously does not buy every device on the market so this is the main way he can find out what he needs to add to support it

**Comment by Kane610** [comment]
Did the issue resolve itself?

**Comment by RZANDBER2006** [comment]
nope, i switched to z2m

**Comment by Kane610** [comment]
> nope, i switched to z2m

I hope it works out for you!
