### ISSUE TITLE
Styrbar Automations deleted after update to 2023.1

### ISSUE THREAD

**Issue by chrizzlibaer** [Kane610/deconz#395]
I am using many Styrbar remotes in my home for triggering different things.

I am very glad that the naming for the buttons is finally fixed, was always a hassle to figure out which button has which name 🙄

But directly after upgrading to 2023.1.0, all of my automations that are triggered by buttons renamed in the upgrade process just got deleted. 

Expected behavior: 
automations are invalid and need to be fixed. 

Actual behavior:
Automations with all conditions and actions are gone.

Possible workaround:
Find Every automation with Styrbar remotes, change the trigger to something else. 
Upgrade. 
Change the automations again. 

When I revert to a 2022.12 release, the automations reappear and are still working. 

Is there a way to upgrade without loosing all the automations so I can fix the triggers afterwards?

That would be awesome...
Thanks!

**Comment by chrizzlibaer** [comment]
Did it manually by reconfiguring all automations triggered by "on" and "off" triggers to any "Dim up" or "Dim down" triggers.
Then updated to 2023.1.4
Afterwards reconfiguring every remote by the correct "dim up", "dim down", "left" and "right" triggers, works correct now.
So i am closing this now.

**Comment by Kane610** [comment]
Sorry! I missed this one, great that you could resolve it!
