### ISSUE TITLE
Unsupported device type ZHAParticulateMatter

### ISSUE THREAD

**Issue by oywino** [Kane610/deconz#531]
Hi, I use deConz (v2.24.beta) + Phoscon + Home Assistant(v.2023.10.3) (all is container based).
I do not have a HomeBridge and I do not use Home kit. I do not use the ZHA integration. I do not have any Matter capable devices, HUB's or controllers.

But I do get the above error message every time I reload the deConz integration (or restart HA):

```
Logger: pydeconz.models
Source: components/deconz/gateway.py:356
First occurred: 10:04:47 PM (1 occurrences)
Last logged: 10:04:47 PM
Unsupported device type ZHAParticulateMatter
```

I have no Idea what "ZHAParticulateMatter" means.

Do you have any idea why I keep getting this error message, and how I can recitfy this?
Can you briefly explain what "ZHAParticulateMatter" is ?

Many thanks in advance.

**Comment by Kane610** [comment]
Hello, this is a new zhatype. I'e updated pydeconz to support it but not yet published an update for home assistant.

**Comment by oywino** [comment]
So is this just a result of me running the latest beta?

**Comment by Kane610** [comment]
> So is this just a result of me running the latest beta?

Hmm. Not sure if it's just beta or also last stable. But it's quite new. It's nothing to worry about. Just an unsupported type in the library

**Comment by oywino** [comment]
Ok, thanks.

**Comment by Kane610** [comment]
Closing this as PR in Home Assistant is up.
