### ISSUE TITLE
ZHAPower (Plug)

### ISSUE THREAD

**Issue by tleegaard** [Kane610/deconz#6]
I get the following error when starting Home Assistant: `Unsupported sensor type ZHAPower (Plug)`. I guess it is from my osram smart+ plug :-)

**Comment by Kane610** [comment]
See this discussion for more details https://github.com/dresden-elektronik/deconz-rest-plugin/issues/432

I'm awaiting more details to add support for this type.

**Comment by Kane610** [comment]
I will probably have something ready for putting in to hass tomorrow for this

**Comment by Kane610** [comment]
Support for ZHAPower has been added as of v32 of this package.

**Comment by timbru31** [comment]
@Kane610 any chance of a port to the regular home-assistant component?

**Comment by Kane610** [comment]
@timbru31 what do you mean? This is used by home assistant deconz component

**Comment by timbru31** [comment]
Yeah sorry, realized it in the meantime, too. I thought it lacked support, since the commit https://github.com/home-assistant/home-assistant/commit/f5d74e07d51b0992d37105e1eb0fbbeca99a32ef is not yet released and my plugs are reported as lights :)
