### ISSUE TITLE
Heiman sirene does not go on

### ISSUE THREAD

**Issue by fonzies83** [Kane610/deconz#61]
Dear,I use Deconz with home assistant and I'm not able to use the Heiman siren.
I try to follow the https://github.com/Kane610/deconz/issues/17 instructions but I don't understand wich is the number\field of my siren.
And also I'm not able to enable debug per component documentation and post relevant part .

Can anyone help me?

Thank you and regards.

**Comment by Kane610** [comment]
Instructions to enable debug: https://www.home-assistant.io/integrations/deconz/#debugging-integration. You can also specify the entity id to use the service

**Comment by Kane610** [comment]
Closing this due to lack of feedback
