### ISSUE TITLE
IKEA badring (Water Leak Sensor)

### ISSUE THREAD

**Issue by no2spc** [Kane610/deconz#610]
The IKEA badring Water Leak Sensor is supported by deCONZ (added in the latest beta version, [v2.27.0-beta](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.27.0-beta) - the [DDF can be found here](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/ikea/badring_water_leak_sensor.json). Is there a way to incorporate the DDF in deconz via Home Assistant prior to a new release of the addon?

**Comment by Kane610** [comment]
This repo has nothing to do with the addon. And the addon only supports stable releases.

From the integration perspective it probably reports what's already supported.

I think once 2.27 comes to the addon it will be possible to post install additional DDFs. But right now it's probably not doable.

Closing as this is unrelated to pydeconz
