### ISSUE TITLE
Add fan support

### ISSUE THREAD

**Issue by Kane610** [Kane610/deconz#63]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/932

**Comment by hgelpke** [comment]
Saw this on an issue I was following. Is there news on fan integration?

**Comment by Kane610** [comment]
I am focusing on a different integration right now so it will probably happen once they add the support in deconz

**Comment by hgelpke** [comment]
Copy. Thank you for the response

**Comment by Kane610** [comment]
Of course

**Comment by gmitch64** [comment]
Going to install my controller this weekend, so was checking for an update on the status. I'll keep an eye out here too.

G

**Comment by jjlawren** [comment]
I just installed one of these and successfully paired it. The light control works fine already. I'd be happy to help test the fan controls if needed.

**Comment by Kane610** [comment]
Fan support should be complete.
