### ISSUE TITLE
Fyrtur Battery status works half the time

### ISSUE THREAD

**Issue by dwarf-rbi** [Kane610/deconz#72]
I have 13 IKEA fyrtur blinds, in different sizes. All have been upgraded to 2.2.009 firmware.
I can only ready battery status from half of them. I can seem to find any pattern on which works and which dont
![image](https://user-images.githubusercontent.com/54988285/88329816-cd01f700-cd2a-11ea-9ed9-6ac74809c093.png)

I have tried pretty much everything within VNC, and the settings. So im not sure if its deCONZ or ikea software that are failing here. I can see lot of other issues have been reporterd regarding the Fyrtur battery, but none are simular to my issue, where some works and others dont.
![1](https://user-images.githubusercontent.com/54988285/88329726-b360af80-cd2a-11ea-9245-6eb52fca6a6c.png)
![2](https://user-images.githubusercontent.com/54988285/88329735-b52a7300-cd2a-11ea-817a-51cd37c7cf28.png)

![3](https://user-images.githubusercontent.com/54988285/88329957-00448600-cd2b-11ea-867f-f89f23df70e4.jpg)

**Comment by Kane610** [comment]
Thanks for reporting but your princess lives in another castle. This GitHub is only for the communication between home assistant and deconz, if there is an issue in deconz you need to report it in that GitHub.

**Comment by Kane610** [comment]
No response from OP, closing.
