### ISSUE TITLE
support for extra states in ZHApresence

### ISSUE THREAD

**Issue by mamrai1** [Kane610/deconz#78]
can we add support for extra states in ZHApresence like 'tampered' and lowbattery'. These states are supported and reported by deconz api but not exposed as binary_sensors in HA. Only 'presence' is exposed in HA. 
e.g. deconz api state report:
"state":{"lastupdated":"2020-10-11T14:43:57.887","lowbattery":false,"presence":false,"tampered":true},"swversion":"20140929","type":"ZHAPresence","uniqueid":"xxx"}

a.  'lowbattery' should be exposed  as binary_sensor with device class battery
b.  'tampered' i think should be exposed as Binary_sensor with device class problem or safety. Or even better a new device class tamper?

**Comment by Kane610** [comment]
Are these really exclusive to zhapresence device types?

**Comment by mamrai1** [comment]
'tampered' and ' low battery' state attribute is supported under (bool type):
ZHAAlarm, ZHACarbonMonoxide, ZHAFire, ZHAOpenClose, ZHAPresence and ZHAWater

**Comment by Kane610** [comment]
Please try out the hass beta to verify that tampering entity works as expected @mamrai1

**Comment by Kane610** [comment]
Low battery sensor will be out with 2022.2 release of Home Assistant.
