### ISSUE TITLE
Last Time Message

### ISSUE THREAD

**Issue by cagnulein** [Kane610/deconz#80]
I would like to have a property for each sensor that it will return the timestamp of the lastest message received.

It will be very useful in order to understand if a sensor is available or not.

What do you think?

**Comment by Kane610** [comment]
Sure it can be added

**Comment by cagnulein** [comment]
@Kane610 if you want I can help to develop it or to test it

**Comment by Kane610** [comment]
Feel free to contribute 👍🏻

**Comment by cagnulein** [comment]
@Kane610 awesome! Just to be sure to do a useful work, where is, in your opinion the correct point to add this property? And also, is there already a similar property in the rest api or you are thinking about deriving it?

**Comment by Kane610** [comment]
It is probably available for all devices and groups and everything so I guess https://github.com/Kane610/deconz/blob/master/pydeconz/deconzdevice.py is the place to put it. IIRC that attribute does exist yes, you can even check the mock data in tests might already contain it

**Comment by cagnulein** [comment]
![Immagine](https://user-images.githubusercontent.com/48216/99192018-be739b80-2770-11eb-9698-4b7e724e5e86.png)

i solved in this way, the state has been alread implemented :) thanks again!
