### ISSUE TITLE
Deconz Integration Connection Issue

### ISSUE THREAD

**Issue by TheAlphaLaw** [Kane610/deconz#93]
Hi!

Recently an HA update has broken quiet a few USB device integrations. All the devices brought in via my Conbee II through your integration are now "unavailable". However, the integration itself still see's all the devices and will update as needed if the integration or removed, or if a new device is added. See error log below:

I'm quiet dependent on this integration as all of the lights/sensors in my home are controlled via HA or Google Home. I can still control the lights via Phoscons, though. 

```
Logger: pydeconz.websocket
Source: /usr/local/lib/python3.8/site-packages/pydeconz/websocket.py:92
First occurred: 11:01:36 AM (136 occurrences)
Last logged: 11:35:21 AM

Unexpected error [Errno 104] Connection reset by peer
```

**Comment by TheAlphaLaw** [comment]
Fixed this.

**Comment by Kane610** [comment]
What was the issue and how did you solve it?

**Comment by TheAlphaLaw** [comment]
The latest version of Deconz W10 desktop app does not communicate with the latest version of HA. Any Deconz version 2.09.01 and under works!

My Setup:

W10
VirtualBox Ubuntu Install
Conbee II Firmware26680700 / Desktop App 2.09.01
Deconz W10 Desktop App
HA Phoscon/Deconz Integration

**Comment by Kane610** [comment]
Works fine with 2.09.3 for me here. Make sure your environment is correctly configured and that no firewall is blocking any port.

**Comment by TheAlphaLaw** [comment]
Software and hardware firewall  were off when testing. The second I install 2.09.3 all items go unavailable in HA. When dropping to 2.09.2 the same occurs. However, the second the install for 2.09.1 finishes, all items are available in HA again.
