### ISSUE TITLE
Getting started with pydeconz

### ISSUE THREAD

**Issue by markicos** [Kane610/deconz#94]
hello there,

i am trying to implement a python code in order to connect a usb Conbee II, to some sensors, but i don´t see any getting started doc or similar.

Looking at the code i can see that all I want to implement in my code is possible, except to search new devices, where can I find more information about it?

Thanks a lot for you work

**Comment by Kane610** [comment]
Rest API documentation: https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/configuration/

Make a new method similar to initialize which calls request with 

`await self.request("put", "/config/", json={"permitjoin": 60})`

Note this is untested and might not work

https://github.com/Kane610/deconz/blob/c89a33b0f72216567209a8cab1e0ebd65111d1d6/pydeconz/gateway.py#L66

**Comment by markicos** [comment]
Thanks it was a very useful help,

Now i am facing a problem, I am trying to use the basic authentification, but it is  reporting always user and password is not recognized. I saw in your __main__.py that you comment the user and pass in kw, have you had problems with it? 

https://github.com/Kane610/deconz/blob/c89a33b0f72216567209a8cab1e0ebd65111d1d6/pydeconz/__main__.py#L39

Later I tested to get into Conbee II thought Web App
I am getting always an error:
![image](https://user-images.githubusercontent.com/44501063/108106651-85f49e00-708e-11eb-8d81-878506bdf251.png)

I am using the same pass than in Phoscon APP where I have no problem. I am doing something wrong...

**Comment by Kane610** [comment]
I should probably improve the main a bit :), what you should do is generate an api key https://github.com/Kane610/deconz/blob/c89a33b0f72216567209a8cab1e0ebd65111d1d6/pydeconz/utils.py#L13

In Phoscon you should open up for pairing of third party applications and then use the async_get_api_key function

**Comment by markicos** [comment]
I was expecting not to use the pairing :(, but in any case thanks a lot...

**Comment by Kane610** [comment]
If you get your credentials right it's just a matter of altering this line with the basic auth parts from async_get_api_key, unfortunately I stopped using the credentials a couple of years ago but it should still work

https://github.com/Kane610/deconz/blob/c89a33b0f72216567209a8cab1e0ebd65111d1d6/pydeconz/gateway.py#L99

**Comment by markicos** [comment]
Thanks, I think the problem is the user not the password, but don't know how to get the proper one, I will give you updated in any case.

**Comment by markicos** [comment]
You will laugh, the default user and password was the ones in your main code, both are `delight` , I though it was something you set previously,  i am getting the apikey without problems.

Thanks a lot

**Comment by Kane610** [comment]
> You will laugh, the default user and password was the ones in your main code, both are `delight` , I though it was something you set previously, i am getting the apikey without problems.
> 
> Thanks a lot

Great! It was so obvious I didn't think I'd need to ask the question 😂

**Comment by markicos** [comment]
Hello,

I have one more question, is it mandatory to run up the deconz software to use the discovery function?, as if i have not this software running i am having allways "[ ]" as response.

**Comment by Kane610** [comment]
No the discovery function is a helper function in cases where you don't have full knowledge of the system or want to provide a better user experience

**Comment by voytecPL** [comment]
Hi,
Where I can find some sample code to get me started.
It would be great to put it in README doc for other to use this package.
I could create something like that if you are OK with it.
I now have API key and can connect to my gateway check sensors etc, but wondering how I could use your code.
Please advise.
Thanks

**Comment by Kane610** [comment]
> Hi,
> Where I can find some sample code to get me started.
> It would be great to put it in README doc for other to use this package.
> I could create something like that if you are OK with it.
> I now have API key and can connect to my gateway check sensors etc, but wondering how I could use your code.
> Please advise.
> Thanks

Feel free to do that 👍🏻 

I think improving the main file is a good way to show case how to set up the basics of the integration. I can probably do that within the next few days.

If you want to delve deep into it everything is done to work with Home Assistant so you can look at the deconz integration to get inspiration. https://github.com/home-assistant/core/tree/dev/homeassistant/components/deconz
